blog_coursework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='posts/')),
    path('posts/', include('posts.urls')),
    path('cv/', include('cv.urls')),
    path('admin/', admin.site.urls),
]

cv/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'cv'

urlpatterns = [
    path('', RedirectView.as_view(url='preview/')),
    path('preview/', views.PreviewView.as_view(), name='preview'),
    path('edit/', views.edit_cv, name='edit'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail')
]

cv/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Credentials(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=500)
    phone = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Qualification(models.Model):
    class QTypes(models.TextChoices):
        SKILLS = 'Skills', _('Skills')
        EDUCATION = 'Education', _('Education')
        CAREER = 'Career', _('Career')
        PROJECTS = 'Projects', _('Projects')

    type = models.CharField(max_length=200, choices=QTypes.choices)
    text = models.TextField()

    def __str__(self):
        return self.type + ' (' + self.text[:15] + '..)'

posts/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __str__(self):
        return self.title

cv/forms.py
from django import forms

from .models import Credentials


class CForm(forms.ModelForm):
    class Meta:
        model = Credentials
        fields = '__all__'

cv/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.forms import modelformset_factory, Textarea

from .models import Credentials, Qualification
from .forms import CForm


types = Qualification.QTypes.values


class PreviewView(generic.base.TemplateView):
    template_name = 'cv/preview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['credentials'] = Credentials.objects.first()
        context['qualifications'] = Qualification.objects.all()
        context['q_types'] = types
        return context


def edit_cv(request):
    QFormSet = modelformset_factory(Qualification, fields=('text', ), widgets={"text": Textarea(attrs={'rows': 6})}, can_delete=True, extra=1)

    if request.method == 'POST':
        credentials_form = CForm(request.POST, instance=Credentials.objects.first())
        formsets = [QFormSet(request.POST, prefix=t) for t in types]

        if credentials_form.is_valid() and all([f.is_valid() for f in formsets]):
            credentials_form.save()
            [save_formset(f) for f in formsets]
            return HttpResponseRedirect(reverse('cv:preview'))
    else:
        credentials_form = CForm(instance=Credentials.objects.first())
        formsets = [QFormSet(prefix=t, queryset=Qualification.objects.filter(type=t)) for t in types]

    return render(request, 'cv/edit.html', {'credentials_form': credentials_form, 'formsets': formsets})


def save_formset(f):
    f.save(commit=False)
    for q in f.new_objects:
        q.type = f.prefix
    f.save()

posts/views.py
from django.views import generic

from .models import Post


class IndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'posts_list'

    def get_queryset(self):
        return Post.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    template_name = 'posts/detail.html'
    model = Post

cv/templates/cv/edit.html
{% extends "base.html" %}
{% load extras %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {% include 'cv/includes/c_form.html' with form=credentials_form %}

        {% for formset in formsets %}
            <div class="py-5">
                <h1 class="text-center">{{ formset | prefix | upper }}</h1>
                {{ formset.management_form }}
                {% for form in formset %}
                    {% include 'cv/includes/q_form.html' with form=form formset=formset %}
                {% endfor %}
            </div>
        {% endfor %}

        <div class="text-center">
            <input class="btn btn-dark btn-lg cv-button" type="submit" value="Update">
        </div>
    </form>
{% endblock %}

cv/templates/cv/includes/c_form.html
{% load widget_tweaks %}

{% for field in form.visible_fields %}
    <div class="form-group row">
        <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
        <div class="col-sm-10">
            {% render_field field class="form-control" %}
        </div>
    </div>
{% endfor %}

cv/templates/cv/includes/errors.html
{% load widget_tweaks %}

{% render_field field class="form-control is-invalid" %}
{% for error in field.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
{% endfor %}

cv/templates/cv/includes/q_form.html
{% load widget_tweaks %}

{{ form.non_field_errors }}

<div class="form-group row">
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    <div class="col-sm-10">
    {% if form.text.errors %}
        {% include 'cv/includes/errors.html' with field=form.text %}
    {% else %}
        {% render_field form.text class="form-control" %}
    {% endif %}
    </div>

    {% if formset.can_delete %}
        <div class="form-check mb-2 mr-sm-2">
            <label for="{{ form.delete.id_for_label }}" class="form-check-label">Remove:</label>
            {{ form.DELETE }}
        </div>
    {% endif %}
</div>

cv/templates/cv/preview.html
{% extends "base.html" %}
{% load extras %}

{% block content %}
    <div class="container jumbotron rounded px-5">
    {% if credentials %}
        <div class="text-right pr-4">
            <h1 class="display-4">{{ credentials.name }}</h1>
            <h3 class="text-muted">{{ credentials.phone }}</h3>
            <h3 class="text-muted">{{ credentials.address }}</h3>
            <h3 class="text-muted">{{ credentials.email }}</h3>
        </div>

        <div class="pl-4">
            {% for type in q_types %}
                <h2>{{ type | upper }}</h2>
                {% for q in qualifications|get:type %}
                    <div class="qualification">{{ q | markdown | safe }}</div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="text-center">
            <a href="{% url 'cv:edit' %}" type="button" class="text-center btn btn-dark btn-lg cv-button">Edit</a>
        </div>
    {% else %}
        <h1>CV not available.</h1>
        <a class="blog-title btn btn-light" href="{% url 'cv:edit' %}" role="button">Create</a>
    {% endif %}
    </div>
{% endblock %}

posts/templates/posts/detail.html
{% extends "base.html" %}
{% load extras %}

{% block content %}
    <div class="blog-post py-3 px-5 text-justify">
        <h2 class="blog-title blog-post-title text-center"><a class="text-dark" href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></h2>
        <p class="blog-post-meta text-muted text-center">{{ post.pub_date }}</p>
        <p class="post-content">{{ post.content | markdown | safe }}</p>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends "base.html" %}
{% load extras %}

{% block content %}
    {% if posts_list %}
        {% for post in posts_list %}
            <div class="blog-post py-3 text-justify">
                <h2 class="blog-title blog-post-title"><a class="text-dark" href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></h2>
                <p class="blog-post-meta text-muted">{{ post.pub_date }}</p>
                <p class="post-content">{{ post.content | markdown | safe }}</p>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-danger" role="alert">
            No available posts!
        </div>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet", type="text/css", href="{% static 'style.css' %}">
    <meta charset="UTF-8">

    <title>Blog Posts</title>
</head>

<body>
    <div class="container pt-2 px-5">

        <div class="container jumbotron p-4 p-md-5 text-white rounded-pill bg-dark text-center">
            <h1 class="blog-title display-4"><a class="logo-link text-light" href="{% url 'posts:index' %}">Blogging website</a></h1>
            <h2 class="blog-title display-5">&#x25CF bridging coursework &#x25CF</h2>
            <a class="blog-title btn btn-light" href="{% url 'cv:preview' %}" role="button">Interactive CV here...</a>
        </div>

        <main role="main" class="px-5">
            {% block content %}
            {% endblock %}
        </main>

        <br>
        <footer class="container">
          <p class="text-center">&copy footer 2020</p>
        </footer>

    </div>
</body>
</html>